### ISSUE TITLE
[Bug] NoMethodError is raised when loading XLSX spreadsheet

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#211]
NoMethodError is raised when loading the attached XLSX spreadsheet.

[Book.xlsx](https://github.com/user-attachments/files/15633907/Book.xlsx)

```
taichi@LAPTOP-TVTKLNFD:rggen
$ rggen -o out --print-backtrace Book.xlsx
[NoMethodError] undefined method `count' for an instance of RgGen::SpreadsheetLoader::Spreadsheet::Cell
backtrace:
    /opt/rbenv/versions/3.3.0/lib/ruby/3.3.0/delegate.rb:91:in `method_missing'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-default-register-map-0.33.0/lib/rggen/default_register_map/bit_field/bit_assignment.rb:102:in `match_bit_assignment?'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-default-register-map-0.33.0/lib/rggen/default_register_map/bit_field/bit_assignment.rb:90:in `preprocess'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-default-register-map-0.33.0/lib/rggen/default_register_map/bit_field/bit_assignment.rb:30:in `block (3 levels) in <top (required)>'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:146:in `instance_exec'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:146:in `block in execute_build_blocks'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:146:in `each'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:146:in `execute_build_blocks'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:141:in `do_build'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature.rb:100:in `build'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature_factory.rb:103:in `build_feature'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature_factory.rb:30:in `block in create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/feature_factory.rb:21:in `block in create_feature'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/feature.rb:16:in `initialize'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/feature_factory.rb:19:in `new'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/feature_factory.rb:19:in `create_feature'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/feature_factory.rb:29:in `create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:91:in `create_feature'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:64:in `block in create_active_features'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:63:in `each'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:63:in `create_active_features'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:58:in `create_features'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:65:in `do_create_features'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:58:in `build_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:33:in `block in create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component.rb:17:in `initialize'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `new'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `create_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:32:in `create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:95:in `create_child'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:76:in `block in create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `each'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:73:in `do_create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:59:in `build_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:33:in `block in create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component.rb:17:in `initialize'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `new'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `create_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:32:in `create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:95:in `create_child'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:76:in `block in create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `each'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:73:in `do_create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:59:in `build_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:33:in `block in create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component.rb:17:in `initialize'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `new'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `create_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:32:in `create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:95:in `create_child'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:76:in `block in create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `each'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/input_base/component_factory.rb:75:in `create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:73:in `do_create_children'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:59:in `build_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:33:in `block in create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component.rb:17:in `initialize'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `new'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:47:in `create_component'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/base/component_factory.rb:32:in `create'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/generator.rb:35:in `load_register_map'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/generator.rb:9:in `run'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/lib/rggen/core/cli.rb:16:in `run'
    /opt/rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rggen-core-0.33.0/exe/rggen:9:in `<top (required)>'
    /opt/rbenv/versions/3.3.0/bin/rggen:25:in `load'
    /opt/rbenv/versions/3.3.0/bin/rggen:25:in `<main>'
```

**Comment by taichi-ishitani** [comment]
By default format, this notation is treated as an integer value.
![image](https://github.com/rggen/rggen/assets/2922232/74cdc934-860e-4896-ac9c-1e7bc0845f03)

Because of this, the above no method error is raised.
